server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Export estático de Next con trailingSlash: /ruta/ -> /ruta/index.html
    location / {
        try_files $uri $uri/index.html $uri.html /index.html;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
